networks:
  app:
    driver: bridge

services:
  composer:
    image: composer:2.2
    networks:
      - app
    tty: true
    volumes:
      - .:/app
      - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
  php:
    image: php:8.4
    networks:
      - app
    tty: true
    volumes:
      - .:/usr/src/app
